import 'package:flutter/material.dart';

final List<DropdownMenuEntry<String>> attribueDropdownItems = [
  DropdownMenuEntry(value: 'Buffet', label: 'Buffet'),
  DropdownMenuEntry(value: 'Child Friendly', label: 'Child Friendly'),
  DropdownMenuEntry(value: 'Fireplace', label: 'Fireplace'),
  DropdownMenuEntry(
      value: 'Luxe awards Plated', label: 'Luxe awards Plated'),
  DropdownMenuEntry(
      value: 'Luxe awards Plated 2019', label: 'Luxe awards Plated 2019'),
  DropdownMenuEntry(
      value: 'Luxe awards Rated 2019', label: 'Luxe awards Rated 2019'),
  DropdownMenuEntry(value: 'Great Views', label: 'Great Views'),
  DropdownMenuEntry(value: 'Live Sport', label: 'Live Sport'),
  DropdownMenuEntry(value: 'Outdoor Seating', label: 'Outdoor Seating'),
  DropdownMenuEntry(value: 'Pet Friendly', label: 'Pet Friendly'),
  DropdownMenuEntry(value: 'Picnics', label: 'Picnics'),
  DropdownMenuEntry(value: 'Romantic', label: 'Romantic'),
  DropdownMenuEntry(value: 'Serves Halaal', label: 'Serves Halaal'),
  DropdownMenuEntry(value: 'Sunsets', label: 'Sunsets'),
  DropdownMenuEntry(value: 'Wheelchair Friendly', label: 'Wheelchair Friendly'),
  DropdownMenuEntry(value: 'WiFi', label: 'WiFi'),
];

final List<DropdownMenuEntry<String>> cuisineDropdownItems = [
  DropdownMenuEntry(value: 'Afghan', label: 'Afghan'),
  DropdownMenuEntry(value: 'African', label: 'African'),
  DropdownMenuEntry(value: 'Afternoon Tea', label: 'Afternoon Tea'),
  DropdownMenuEntry(value: 'American', label: 'American'),
  DropdownMenuEntry(value: 'Asian/Oriental', label: 'Asian/Oriental'),
  DropdownMenuEntry(value: 'Bistro', label: 'Bistro'),
  DropdownMenuEntry(value: 'Breakfast', label: 'Breakfast'),
  DropdownMenuEntry(value: 'Burgers', label: 'Burgers'),
  DropdownMenuEntry(value: 'Charcuterie Boards', label: 'Charcuterie Boards'),
  DropdownMenuEntry(value: 'Chinese', label: 'Chinese'),
  DropdownMenuEntry(value: 'Coffee Shop', label: 'Coffee Shop'),
  DropdownMenuEntry(value: 'Contemporary', label: 'Contemporary'),
  DropdownMenuEntry(value: 'Deli', label: 'Deli'),
  DropdownMenuEntry(value: 'European', label: 'European'),
  DropdownMenuEntry(value: 'Fine Dining', label: 'Fine Dining'),
  DropdownMenuEntry(value: 'French', label: 'French'),
  DropdownMenuEntry(value: 'Fusion', label: 'Fusion'),
  DropdownMenuEntry(value: 'Gastropub', label: 'Gastropub'),
  DropdownMenuEntry(value: 'Greek', label: 'Greek'),
  DropdownMenuEntry(value: 'Indian', label: 'Indian'),
  DropdownMenuEntry(value: 'Indonesian', label: 'Indonesian'),
  DropdownMenuEntry(value: 'International', label: 'International'),
  DropdownMenuEntry(value: 'Italian', label: 'Italian'),
  DropdownMenuEntry(value: 'Japanese', label: 'Japanese'),
  DropdownMenuEntry(value: 'Korean', label: 'Korean'),
  DropdownMenuEntry(value: 'Lebanese', label: 'Lebanese'),
  DropdownMenuEntry(value: 'Mediterranean', label: 'Mediterranean'),
  DropdownMenuEntry(value: 'Mexican', label: 'Mexican'),
  DropdownMenuEntry(value: 'Middle Eastern', label: 'Middle Eastern'),
  DropdownMenuEntry(value: 'Pizza', label: 'Pizza'),
  DropdownMenuEntry(value: 'Portuguese', label: 'Portuguese'),
  DropdownMenuEntry(value: 'Pub Meals', label: 'Pub Meals'),
  DropdownMenuEntry(value: 'Seafood', label: 'Seafood'),
  DropdownMenuEntry(value: 'South African', label: 'South African'),
  DropdownMenuEntry(value: 'Spanish', label: 'Spanish'),
  DropdownMenuEntry(value: 'Steakhouse', label: 'Steakhouse'),
  DropdownMenuEntry(value: 'Sushi', label: 'Sushi'),
  DropdownMenuEntry(value: 'Tapas', label: 'Tapas'),
  DropdownMenuEntry(value: 'Thai', label: 'Thai'),
  DropdownMenuEntry(value: 'Turkish', label: 'Turkish'),
  DropdownMenuEntry(value: 'Vegan Friendly', label: 'Vegan Friendly'),
  DropdownMenuEntry(value: 'Vegetarian Friendly', label: 'Vegetarian Friendly'),
  DropdownMenuEntry(value: 'Vietnamese', label: 'Vietnamese'),
];

final List<DropdownMenuEntry<String>> typesDropdownItems = [
  DropdownMenuEntry(value: 'Real-Time', label: 'Real Time'),
  DropdownMenuEntry(value: 'Request', label: 'Request'),
];
